solana-playground/solana-playground

.gitignore
client/src/components/Panels/Side/Right/Test/FetchableAccount.tsx
client/src/components/Panels/Side/Right/Test/Test.tsx
client/src/utils/pg/account.ts
client/src/utils/pg/common.ts

This PR updates the Test panel to add support for displaying the accounts parsed from the IDL, and for each of them fetching all accounts or one account by its public key.
This allows inspecting the results of an instruction immediately and without leaving the Test UI. 
Demo: 
https://user-images.githubusercontent.com/1711350/179417905-1f1794cf-a95b-4e0c-880e-5ffb1a201c2c.mov
Implementation details:
- I've tried to keep the styling consistent with the existing instructions. I'm not experienced with styled components though so please let me know if I did anything wrong! 
- The new component used to display a row of `Account` data (in a Foldable, similar to instructions) is `FetchableAccount`
- There's a bit of a hack to override the `toJson` method on the `BN` object. By default it's a hex …

Test panel: add support for accounts

---

client/src/components/Panels/Side/Right/Test/FetchableAccount.tsx

This PR adds some missing validation/error handling mentioned in #40 
- If the entered address is not a valid public key, input shows an error and fetch entered button is disabled:
- If the playground wallet is not connected, both buttons are disabled:
- RPC errors (such as an incorrect address being entered) are displayed inline:
Closes #40

Account fetch: add input validation + error handling

---

client/src/components/Panels/Main/Editor/Monaco/declarations/pg.raw.d.ts
client/src/utils/pg/wallet.ts

This PR slightly modifies the `PgWallet` interface to make `keypair` accessible.
This allows writing client code like:
```ts
const transactionSignature = await web3.sendAndConfirmTransaction(
pg.connection,
transaction,
[pg.wallet.keypair]
);
```
This is a lot simpler than using `pg.wallet.signTransaction` and then sending it as a raw transaction. I think that's currently how you'd need to send a transaction?
Note that this doesn't have any security implications, client code can already run `pg.wallet._kp` to get at the currently private field.
If we do need to hide the keypair for security then maybe we could add `_kp` to the blacklisted words? But I do think it's a lot nicer to be able to access the keypair in client code if possible!

Add keypair to the wallet interface so it can be used in client code

---

client/src/utils/pg/client/client.ts

Stops you doing evil things like `console.log(eval("global" + "This" + ".pg"));`
Since both of these execute code given as a string, they allow bypassing the blacklist by concatenation

Blacklist eval and Function in client code

---

client/src/utils/pg/client/client.ts

This fixes a bug where code after the import was also being removed

Use the same import regex when removing imports

---

client/src/constants/connection.ts

Hey there! Ajay from the Alchemy team. Given our new Solana support, I added the latest Alchemy devnet public RPC Url for Solana. Pls let me know if there are any questions, appreciate what you guys are doing at SOL Playground :) I'm definitely using your product for our tutorials!

Add Alchemy Devnet RPC Endpoint

---

client/src/components/Panels/Side/Right/Test/CodeResult.tsx
client/src/components/Panels/Side/Right/Test/FetchableAccount.tsx
client/src/components/Panels/Side/Right/Test/ListenableEvent.tsx
client/src/components/Panels/Side/Right/Test/Test.tsx
client/src/hooks/useBigNumberJson.tsx

This PR adds an events section to the test page. It lists the events in the anchor IDL, listens for instances of those events and displays them in a foldable section.
https://user-images.githubusercontent.com/1711350/201411651-efe85006-fa13-48b7-b63a-1e648d1ce605.mov
This means that you can verify/experiment with the events emitted by your program while testing it in playground.
I've refactored out some stuff that's shared with the accounts section: the styled code block, and the hacky replacement of `BN.toJson` to make large numbers display nicely.
Note that the event listeners are only active when the test page is open, they're cleaned up on navigation away and the recorded events are reset too. 
Closes #73

Add events to the Test page, display recorded events from the program

---

vscode/src/commands/create/anchor.ts
vscode/src/commands/create/seahorse.ts

The seahorse project create was erroring on the check for an existing `programs/` directory, because it initializes an Anchor project first. The nesting when there are existing files also isn't appropriate for seahorse.
This PR updates the Seahorse create to write Seahorse files directly after the Anchor create. This avoids the checks and nesting of `processCreate` which aren't suitable when we know there are existing files (the Anchor ones).

Vscode: Fix seahorse project generate

---

client/src/pages/ide/Panels/Main/MainView/Editor/CodeMirror/CodeMirror.tsx
client/src/utils/pg/explorer/explorer.ts

This PR changes the program ID update logic to support the ID being in any rust file. This will allow building an Anchor project where the id is not declared in lib.rs
- Build files are now prioritised, with lib.rs and id.rs coming first followed by everything else
- The declare_id regex check is done on all build files in priority order, not just lib.rs
- When the regex matches we stop checking future files. In practice this means that if the declare_id is in lib.rs or id.rs then it'll be updated quickly and no other files will be checked. If it's in some other file it'll be detected but will be a bit slower as we check eg lib.rs first
- While I think we only support single file Seahorse projects for now, I've added the same behaviour for Python (though no files are prioritised) so that …

Support declare_id in any rust file

---

wasm/Cargo.lock
wasm/solana-client/src/client.rs
wasm/solana-client/src/methods/mod.rs
wasm/solana-client/src/methods/simulate_transaction.rs
wasm/solana-client/src/utils/rpc_response.rs

- added both `simulate_transaction_with_config` and `simulate_transaction` methods to wasm solana client
- updated `SimulateTransactionResponse` to return the [object](https://docs.solana.com/api/http#simulatetransaction) that is expected from the `simulateTransaction` Http method instead of `Signature` type. Mirroring what is found in the [Solana RPC Client](https://github.com/solana-labs/solana/blob/6e5615e32dfd20730f9c3a65bb211512d867e103/rpc-client-api/src/response.rs#L416-#L424)

Add `simulate_transaction` methods to wasm solana client 

---

README.md
wasm/Cargo.lock
wasm/anchor-cli/Cargo.toml
wasm/solana-cli/Cargo.toml
wasm/solana-cli/src/utils/memo.rs
wasm/solana-client/Cargo.toml
wasm/solana-client/README.md
wasm/utils/solana-extra/Cargo.toml
wasm/utils/solana-extra/src/program/vote/vote_state/mod.rs

- Upgrades Solana dependencies to 1.14.16.
- Upgrades `anchor-cli-wasm` version to 0.27.0 to mirror the latest Anchor release.

Upgrade Solana to 1.14.16

---

client/src/utils/pg/theme/theme.ts
client/yarn.lock
wasm/build.sh

On mac os the sed command needs an extra parameter to tell it not to backup the files. 
And the themes can have an old key, which doesn't exists, so i added a fallback to default theme.

Make build script work on macOS and handle invalid theme key

---

client/src/tutorials/TinyAdventure/files/lib.rs
client/src/tutorials/TinyAdventureTwo/files/lib.rs

Fixed comment in; 
TinyAdventure: in the `Initialize` account struct
(u8 = 8 bits unsigned integer = 8 bytes)  changed to (u8 = 8 bits unsigned integer = 1 byte) 
TinyAdventureTwo: in the `InitializeLevelOne` account struct
(u8 = 8 bits unsigned integer = 8 bytes)  changed to (u8 = 8 bits unsigned integer = 1 byte)

comments fix

---

README.md
client/src/components/EditorWithTabs/Editor/Home/resources.ts
client/src/frameworks/seahorse/files/src/fizzbuzz.py
client/src/frameworks/seahorse/from.md
client/src/frameworks/seahorse/from.ts
client/src/tutorials/HelloSeahorse/pages/1.md
client/yarn.lock
vscode/src/commands/create/seahorse.ts
vscode/yarn.lock
wasm/Cargo.lock
wasm/seahorse-compile/Cargo.toml
wasm/seahorse-compile/src/lib.rs

This is a part of the larger migration from the deprecated [seahorse-lang](https://seahorse-lang.org/) to [seahorse-dev](https://www.seahorse.dev/) which will be maintained by me.
Crate: https://crates.io/crates/seahorse-dev
Github: https://github.com/solana-developers/seahorse

Migrate from deprecated seahorse-lang to seahorse-dev

---

client/src/utils/pg/client/client.ts

This regex presupposes that imports will have specifiers, or whatever they're called. This PR aims to enable ‘bare’ imports like this:
```ts
import "foo";
```
The next PR in this stack (#163) makes use of this.

feature: allow bare imports in clients

---

client/src/commands/deploy/deploy.ts
client/src/commands/sugar/commands/deploy/collection.ts
client/src/components/CodeBlock/highlight.ts
client/src/components/EditorWithTabs/Editor/Monaco/languages/rust/rust-analyzer/rust-analyzer.ts
client/src/components/EditorWithTabs/Editor/Monaco/languages/typescript/declarations/declarations.ts
client/src/components/EditorWithTabs/Editor/Monaco/languages/typescript/declarations/global.ts
client/src/components/EditorWithTabs/Editor/Monaco/languages/typescript/declarations/importable.ts
client/src/components/EditorWithTabs/Editor/Monaco/languages/typescript/init.ts
client/src/frameworks/anchor/to.ts
client/src/utils/pg/client/client.ts
client/src/utils/pg/common.ts

Each commit in this PR rolls up serial awaits and await-in-a-loops into a `Promise.all()`
I didn't _really_ test this rigorously.
I did however take some before/after Lighthouse scores loading the playground in a browser.
| Before | After |
|---|---|
|![image](https://github.com/solana-playground/solana-playground/assets/13243/663a3f49-6179-46cd-9ee0-7cb684f81490)|![image](https://github.com/solana-playground/solana-playground/assets/13243/650bd806-0fff-47e2-8968-ad2e70c92ce2)|

Parallelize awaits

---

client/yarn.lock

Just a version bump that updated the version of `@solana/spl-token` in yarn.lock
Tested locally to fix #173

Update @solana/spl-token to 0.3.9

---

client/src/frameworks/seahorse/files/src/fizzbuzz.py
client/yarn.lock
vscode/src/commands/create/seahorse.ts
vscode/yarn.lock
wasm/Cargo.lock
wasm/seahorse-compile/Cargo.toml

- Update Playground to the latest version of Seahorse
- Most importantly, includes https://github.com/solana-developers/seahorse/pull/10 which fixes Seahorse for Anchor 0.29.0

Update to seahorse-dev 0.2.0

---

client/src/components/SearchBar/SearchBar.tsx

I'm not 100% about this fix, I might be missing some nuance about how search bar items work
But the reason pasting was not working is because `item.value ||= clipboardText` was never updating, because `item.value` was truthy:
This PR changes it to always replace `item.value` with the pasted text
~~An alternative fix would be to remove the `{current: true}` from the Custom item, so that `item.value` is just whatever that field contains, but I'm not sure what that represents/would do.~~
Actually I guess that wouldn't work because then you couldn't paste unless the field was empty. I'm not sure if there are circumstances where we shouldn't change `item.value` on paste though. 
Fixes #188

Allow pasting into fields in test UI

---

README.md

Ensure wasm-pack is installed before trying to build locally in README: 
wasm-pack: https://rustwasm.github.io/wasm-pack/installer/
If not installed yarn will output `../wasm/build.sh: line 86: wasm-pack: command not found` when attempting to build locally.

Ensure wasm-pack is installed before trying to build locally in README
